/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_wtopolski_android_polishnotation_JniHelper */

#ifndef _Included_pl_wtopolski_android_polishnotation_JniHelper
#define _Included_pl_wtopolski_android_polishnotation_JniHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_wtopolski_android_polishnotation_JniHelper
 * Method:    convertToNotation
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pl_wtopolski_android_polishnotation_JniHelper_convertToNotation
  (JNIEnv *, jclass, jstring);

/*
 * Class:     pl_wtopolski_android_polishnotation_JniHelper
 * Method:    countValueFromNotation
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_pl_wtopolski_android_polishnotation_JniHelper_countValueFromNotation
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
